@file:Suppress("TooManyFunctions")
package org.mindanchor.letters

import android.app.Notification
import android.app.NotificationManager
import android.app.PendingIntent
import android.app.Service
import android.content.Context
import android.content.Intent
import android.content.pm.PackageManager
import android.os.Build
import android.os.IBinder
import android.os.PowerManager
import androidx.core.app.NotificationCompat
import androidx.core.content.ContextCompat
import java.time.LocalDate
import java.util.concurrent.atomic.AtomicBoolean
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.SupervisorJob
import kotlinx.coroutines.cancel
import kotlinx.coroutines.launch
import org.mindanchor.HomeActivity
import org.mindanchor.R
import org.mindanchor.notifications.Channels

/**
 * v0.32.1: the foreground service that hosts the on-device
 * letter generation.
 *
 * ## Why a foreground service
 *
 * The letter is generated by the Q2_K Phi-4-mini on the
 * phone, at roughly 0.1-0.5 tok/s on a 1.8 GB MemAvailable
 * handset. A full 600-token letter takes 20-100 minutes —
 * the user accepts this as the "overnight letter" design
 * (the letter is ready when they wake up).
 *
 * Pre-v0.32.1, the work ran in a coroutine launched from
 * the Letters inbox's [androidx.compose.runtime.rememberCoroutineScope].
 * That scope is tied to the Composable's lifecycle: it is
 * cancelled when the user navigates away, when the activity
 * is destroyed, and — on a memory-constrained phone — when
 * the OS kills the process to reclaim RAM while the user
 * sleeps. v0.31.2's 50-minute test produced zero letters
 * saved; the process was reaped mid-decode.
 *
 * A foreground service fixes this. The service:
 *
 *  1. Promotes itself to the foreground within the
 *     `onStartCommand` grace window with an ongoing
 *     notification on [Channels.LETTERS_GENERATION], so the
 *     Android 12+ background-start restrictions do not kill
 *     the work.
 *
 *  2. Holds a [PowerManager.PARTIAL_WAKE_LOCK] for the
 *     duration of the generation. CPU-heavy work is
 *     throttled when the screen is off, and the wake lock
 *     is the canonical way to tell the device "this work
 *     needs real compute, do not down-clock me". The lock
 *     is acquired in `onStartCommand` and released in
 *     `onDestroy`.
 *
 *  3. Uses [foregroundServiceType] `dataSync` in the
 *     manifest, paired with the
 *     `FOREGROUND_SERVICE_DATA_SYNC` permission that
 *     [AppWatchService] already uses. The Android 14+
 *     service-type rules require both, and the
 *     [LettersGenerationServiceManifestFindingTest] pins
 *     the pair.
 *
 *  4. Returns [START_NOT_STICKY] from `onStartCommand`. A
 *     process kill is the worst case the design has to
 *     survive; auto-restarting mid-letter would waste
 *     battery and risk a duplicate save (the seed is
 *     derived from the prompt, so the duplicate would be
 *     identical — but the second run would still be
 *     unnecessary compute). The user re-taps to retry.
 *
 *  5. Guards re-entry with [isRunning]. Two rapid taps on
 *     "Generate now" only kick off one generation; the
 *     second start is a no-op (the foreground promotion
 *     runs, then the early-return path ends the service).
 *
 * ## The notification lifecycle
 *
 *  - On start: ongoing notification, "Generating tonight's
 *    letter — this takes 30–60 minutes on this phone." The
 *    icon is in the status bar but IMPORTANCE_LOW keeps
 *    it off the heads-up / lock-screen / sound path; the
 *    user already saw a Toast when they tapped, this is
 *    the "still running" signal, not a new alert.
 *  - On success: the ongoing notification is replaced by
 *    a one-shot "Tonight's letter is ready" with an
 *    action that opens the inbox. The ongoing icon
 *    disappears.
 *  - On failure: the ongoing notification is replaced by
 *    a one-shot "Letter generation didn't complete" with
 *    an action that re-opens the inbox. The user can tap
 *    "Generate now" to retry.
 *
 *  The notification is not a progress widget. The model
 *  runs at the user's CPU's pace; a token count would
 *  just confirm "yes, it is still slow". The ongoing
 *  icon's presence is the alive signal; its disappearance
 *  (replaced by the done/failed notification) is the
 *  finished signal.
 *
 * ## Threading
 *
 *  - `onStartCommand` runs on the main thread.
 *  - The generation runs on [serviceScope]
 *    (a [SupervisorJob] + [Dispatchers.IO] scope), so a
 *    failure in the coroutine does not crash the service.
 *  - The scope is cancelled in `onDestroy`, which releases
 *    the wake lock. If the OS kills the service the same
 *    teardown runs on next start.
 *
 * ## What this service does NOT do
 *
 *  - It does not save partial output. The whole point of
 *    the "overnight letter" is one clean run; saving a
 *    half-finished decode would put garbage in the inbox.
 *    A killed run is a failed run, surfaced to the user
 *    via the failure notification.
 *  - It does not survive a process kill. The user can
 *    re-tap "Generate now". A future WorkManager chunked
 *    variant would persist the state between chunks, but
 *    the design today is "one clean run or no letter
 *    today".
 */
class LettersGenerationService : Service() {

    private val serviceScope = CoroutineScope(SupervisorJob() + Dispatchers.IO)
    private var wakeLock: PowerManager.WakeLock? = null

    override fun onBind(intent: Intent?): IBinder? = null

    override fun onCreate() {
        super.onCreate()
        // The channel is created once at process start by
        // [org.mindanchor.notifications.Channels.ensureAll].
        // The notification builder below assumes the channel
        // exists. If a future process-start change moves the
        // channel creation later than service start (it
        // doesn't today), the builder will create it lazily
        // on the first `notify` call.
    }

    override fun onStartCommand(intent: Intent?, flags: Int, startId: Int): Int {
        // Re-entry guard. The user can tap "Generate now"
        // twice in a row; the second start returns
        // immediately so we do not stack two generations on
        // the same model file (the native side has no
        // inter-call mutex, and a second llama_init_from_model
        // on the same process would double the resident
        // memory).
        if (!isRunning.compareAndSet(false, true)) {
            // The previous generation's foreground is still
            // up; we are not asked to do anything new. End
            // this redundant start. The previous service
            // keeps running.
            stopSelf(startId)
            return START_NOT_STICKY
        }

        // Acquire the wake lock BEFORE startForeground so
        // the CPU is held at full clock for the decode even
        // if the screen is off.
        acquireWakeLock()

        // Foreground promotion must happen within ~5 seconds
        // of the start command on Android 12+. The ongoing
        // notification is the user's "this is alive" signal;
        // the same notification is later replaced by the
        // success / failure notification when generation
        // ends.
        startForeground(NOTIFICATION_ID_ONGOING, buildOngoingNotification())

        // Run the work. The scope outlives this function;
        // the coroutine continues to decode even if the
        // process is backgrounded and the activity is
        // destroyed.
        serviceScope.launch {
            try {
                val body = runGeneration()
                if (body != null) {
                    onGenerationSucceeded(body)
                } else {
                    onGenerationFailed(getString(R.string.letters_generation_failed_empty))
                }
            } catch (t: Throwable) {
                // A model that OOMs, a NarrationGuard that
                // crashes inside its judge(), a DataStore
                // write that throws — all surface here. The
                // letter is not saved; the user sees the
                // failure notification.
                android.util.Log.e(TAG, "letter generation failed", t)
                onGenerationFailed(
                    t.message ?: getString(R.string.letters_generation_failed_unknown),
                )
            } finally {
                isRunning.set(false)
                stopSelf(startId)
            }
        }

        return START_NOT_STICKY
    }

    override fun onDestroy() {
        // Cancel any in-flight work and release the wake
        // lock. The scope's children are the generation
        // coroutine; cancelling it here is a no-op if it
        // already finished.
        serviceScope.cancel()
        releaseWakeLock()
        super.onDestroy()
    }

    /**
     * The generation work: collect the week's data, ask the
     * model for a letter, return the body (or null for
     * "this run produced no letter — that is a normal
     * outcome, not a failure").
     *
     * Pulled out of the [onStartCommand] lambda so the
     * test can drive the same code path without spinning
     * up a Service.
     */
    private suspend fun runGeneration(): String? {
        val appContext = applicationContext
        val week = WeekDataCollector(appContext).collectLastWeek()
        return LetterWriter(appContext).write(week)
    }

    private suspend fun onGenerationSucceeded(body: String) {
        val appContext = applicationContext
        runCatching {
            val today = LocalDate.now()
            LetterStore(appContext).saveUserLetter(today, body)
        }
        postCompletionNotification(body)
    }

    private fun onGenerationFailed(reason: String) {
        postFailureNotification(reason)
    }

    private fun acquireWakeLock() {
        if (wakeLock?.isHeld == true) return
        val pm = getSystemService(Context.POWER_SERVICE) as? PowerManager ?: return
        wakeLock = pm.newWakeLock(
            PowerManager.PARTIAL_WAKE_LOCK,
            "$TAG::generation",
        ).apply {
            // Generous cap: 90 minutes. The 30-60 min
            // design has headroom; a 90 min ceiling lets a
            // throttled device finish without the lock
            // timing out mid-decode. A run that genuinely
            // takes longer is the failure path; the user
            // re-taps.
            acquire(WAKE_LOCK_TIMEOUT_MS)
        }
    }

    private fun releaseWakeLock() {
        runCatching {
            if (wakeLock?.isHeld == true) wakeLock?.release()
        }
        wakeLock = null
    }

    private fun buildOngoingNotification(): Notification {
        return NotificationCompat.Builder(this, CHANNEL_ID)
            .setSmallIcon(android.R.drawable.ic_popup_reminder)
            .setContentTitle(getString(R.string.letters_generation_ongoing_title))
            .setContentText(getString(R.string.letters_generation_ongoing_text))
            .setOngoing(true)
            .setOnlyAlertOnce(true)
            .setPriority(NotificationCompat.PRIORITY_LOW)
            .setCategory(NotificationCompat.CATEGORY_PROGRESS)
            .build()
    }

    private fun postCompletionNotification(body: String) {
        if (!hasPostNotificationsPermission()) return
        val manager = getSystemService(NotificationManager::class.java) ?: return
        val preview = body.lineSequence().take(2).joinToString(separator = "\n")
        val openIntent = PendingIntent.getActivity(
            this,
            NOTIFICATION_ID_COMPLETE,
            Intent(this, HomeActivity::class.java)
                .setAction(LetterScheduler.ACTION_OPEN_LETTER)
                .putExtra("letter_date", LocalDate.now().toString())
                .addFlags(Intent.FLAG_ACTIVITY_CLEAR_TOP or Intent.FLAG_ACTIVITY_SINGLE_TOP),
            PendingIntent.FLAG_UPDATE_CURRENT or PendingIntent.FLAG_IMMUTABLE,
        )
        val notification = NotificationCompat.Builder(this, COMPLETE_CHANNEL_ID)
            .setSmallIcon(android.R.drawable.ic_dialog_email)
            .setContentTitle(getString(R.string.letters_generation_done_title))
            .setContentText(preview)
            .setStyle(NotificationCompat.BigTextStyle().bigText(body))
            .setContentIntent(openIntent)
            .setAutoCancel(true)
            .setPriority(NotificationCompat.PRIORITY_DEFAULT)
            .setCategory(NotificationCompat.CATEGORY_MESSAGE)
            .build()
        manager.notify(NOTIFICATION_ID_COMPLETE, notification)
    }

    private fun postFailureNotification(reason: String) {
        if (!hasPostNotificationsPermission()) return
        val manager = getSystemService(NotificationManager::class.java) ?: return
        val openIntent = PendingIntent.getActivity(
            this,
            NOTIFICATION_ID_FAILED,
            Intent(this, HomeActivity::class.java)
                .setAction(LetterScheduler.ACTION_OPEN_LETTER)
                .addFlags(Intent.FLAG_ACTIVITY_CLEAR_TOP or Intent.FLAG_ACTIVITY_SINGLE_TOP),
            PendingIntent.FLAG_UPDATE_CURRENT or PendingIntent.FLAG_IMMUTABLE,
        )
        val notification = NotificationCompat.Builder(this, COMPLETE_CHANNEL_ID)
            .setSmallIcon(android.R.drawable.ic_dialog_alert)
            .setContentTitle(getString(R.string.letters_generation_failed_title))
            .setContentText(getString(R.string.letters_generation_failed_text, reason))
            .setContentIntent(openIntent)
            .setAutoCancel(true)
            .setPriority(NotificationCompat.PRIORITY_DEFAULT)
            .setCategory(NotificationCompat.CATEGORY_ERROR)
            .build()
        manager.notify(NOTIFICATION_ID_FAILED, notification)
    }

    private fun hasPostNotificationsPermission(): Boolean {
        return ContextCompat.checkSelfPermission(
            this,
            android.Manifest.permission.POST_NOTIFICATIONS,
        ) == PackageManager.PERMISSION_GRANTED
    }

    companion object {
        private const val TAG = "LettersGeneration"

        /** The ongoing-foreground channel. Different from the
         *  success/failure channel because the importance
         *  differs (LOW ongoing vs DEFAULT one-shot). */
        private const val CHANNEL_ID = Channels.LETTERS_GENERATION

        /** The success / failure channel reuses the existing
         *  letters channel — the same one [LetterScheduler]
         *  uses for the morning letter, IMPORTANCE_DEFAULT
         *  with a BigText preview. */
        private const val COMPLETE_CHANNEL_ID = Channels.LETTERS

        private const val NOTIFICATION_ID_ONGOING = 0x710A
        private const val NOTIFICATION_ID_COMPLETE = 0x710B
        private const val NOTIFICATION_ID_FAILED = 0x710C

        /** 90 min cap on the wake lock. See [acquireWakeLock]. */
        private const val WAKE_LOCK_TIMEOUT_MS = 90L * 60L * 1000L

        /**
         * Re-entry guard. Shared across all instances of
         * the service in the process (the OS may create
         * more than one on rapid restarts). [AtomicBoolean]
         * is the right shape: one writer (the service
         * thread that wins the CAS), many readers (the
         * same thread re-checking on a second start).
         */
        private val isRunning = AtomicBoolean(false)

        /**
         * The intent a caller fires to start a generation.
         * The intent carries no payload — the work is
         * "today's letter", and "today" is a function of
         * the system clock at run time, not at start time.
         */
        fun intent(context: Context): Intent =
            Intent(context, LettersGenerationService::class.java)

        /**
         * True when a generation is in progress. The
         * inbox's "Generate now" button is disabled
         * while this is true so the user does not see
         * a misleading second Toast.
         */
        val running: Boolean get() = isRunning.get()
    }
}
