package org.mindanchor.launcher

import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.PaddingValues
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.padding
import androidx.compose.material3.AlertDialog
import androidx.compose.material3.FilterChip
import androidx.compose.material3.Button
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.OutlinedTextField
import androidx.compose.material3.Text
import androidx.compose.material3.TextButton
import androidx.compose.runtime.Composable
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableIntStateOf
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue
import androidx.compose.ui.Modifier
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import org.mindanchor.friction.DearMan

/**
 * The DBT Module 4 (DEAR MAN / GIVE / FAST) "tough
 * conversation" helper. A 4-step Composable flow:
 *
 *  1. **Situation.** Free-text one-or-two-sentence
 *     prompt: "What's the conversation about?"
 *  2. **Priority.** Three-button picker: Objective,
 *     Relationship, Self-respect.
 *  3. **Script.** A one-page template generated by
 *     [DearMan.scriptFor], one line per skill letter.
 *  4. **Save.** Hands the script to the caller's
 *     [onSave] callback (the caller writes to
 *     [org.mindanchor.letters.LetterStore.save]).
 *
 * The flow never overwrites the user's words: the
 * Situation is verbatim, the Skill is rule-based
 * (no LLM), and the script is a template the user
 * fills in. v0.26+ (Phase 1 G-23).
 *
 * ## Why a 4-step flow and not a single textarea
 *
 * The 4 steps mirror the Linehan 1993 framing: pick
 * the priority first, then the skill follows. A
 * single textarea would default to DEAR MAN (the
 * most-taught DBT sub-skill) and skip the priority
 * choice. The flow is the discipline.
 *
 * ## Why "if it would help" framing
 *
 * The dialog title is "If you have a hard conversation
 * coming up…" — not "You should plan your hard
 * conversation". The first frame gives the user a
 * tool; the second is a directive. v0.26+ is
 * BPD-safe by design.
 */
@Composable
fun DearManDialog(
    onDismiss: () -> Unit,
    onSave: (script: String) -> Unit,
) {
    var step by remember { mutableIntStateOf(0) }
    var situation by remember { mutableStateOf("") }
    var priority by remember { mutableStateOf<DearMan.Priority?>(null) }

    AlertDialog(
        onDismissRequest = onDismiss,
        title = { Text(text = "If you have a hard conversation coming up…") },
        text = {
            Column(
                verticalArrangement = Arrangement.spacedBy(8.dp),
                modifier = Modifier.padding(PaddingValues(0.dp)),
            ) {
                when (step) {
                    0 -> StepSituation(
                        situation = situation,
                        onSituationChange = { situation = it },
                    )
                    1 -> StepPriority(
                        picked = priority,
                        onPick = { priority = it },
                    )
                    2 -> StepScript(
                        situation = situation,
                        priority = priority ?: DearMan.Priority.OBJECTIVE,
                    )
                    else -> Unit
                }
            }
        },
        confirmButton = {
            when (step) {
                0 -> {
                    Button(
                        onClick = { step = 1 },
                        enabled = situation.isNotBlank(),
                    ) { Text("Next") }
                }
                1 -> {
                    Button(
                        onClick = { step = 2 },
                        enabled = priority != null,
                    ) { Text("Next") }
                }
                2 -> {
                    Button(onClick = {
                        val script = DearMan.scriptFor(
                            priority = priority ?: DearMan.Priority.OBJECTIVE,
                            situation = situation,
                        )
                        onSave(script)
                    }) { Text("Save as Letter") }
                }
                else -> Unit
            }
        },
        dismissButton = {
            when (step) {
                0 -> TextButton(onClick = onDismiss) { Text("Cancel") }
                else -> TextButton(onClick = { step -= 1 }) { Text("Back") }
            }
        },
    )
}

@Composable
private fun StepSituation(
    situation: String,
    onSituationChange: (String) -> Unit,
) {
    Column(verticalArrangement = Arrangement.spacedBy(8.dp)) {
        Text(text = "What's the conversation about?", fontWeight = FontWeight.SemiBold)
        OutlinedTextField(
            value = situation,
            onValueChange = onSituationChange,
            singleLine = false,
            minLines = 2,
            maxLines = 4,
            modifier = Modifier.fillMaxWidth(),
        )
    }
}

@Composable
private fun StepPriority(
    picked: DearMan.Priority?,
    onPick: (DearMan.Priority) -> Unit,
) {
    Column(verticalArrangement = Arrangement.spacedBy(8.dp)) {
        Text(text = "What matters most?", fontWeight = FontWeight.SemiBold)
        // CodeRabbit review 2026-08-24 (PR #38):
        // the previous version used AssistChip with an
        // ignored `picked` parameter — detekt flagged
        // the unused parameter, and the chip's
        // selected state never changed. Switched to
        // FilterChip with `selected` bound to the
        // current `picked` value; also replaced the
        // deprecated `values()` with `entries`.
        DearMan.Priority.entries.forEach { p ->
            FilterChip(
                selected = picked == p,
                onClick = { onPick(p) },
                label = { Text(text = p.label) },
                modifier = Modifier.fillMaxWidth(),
            )
        }
    }
}

@Composable
private fun StepScript(
    situation: String,
    priority: DearMan.Priority,
) {
    val skill = DearMan.skillFor(priority)
    Column(verticalArrangement = Arrangement.spacedBy(8.dp)) {
        Text(
            text = "Fill in one line per letter.",
            style = MaterialTheme.typography.bodyMedium,
        )
        Text(
            text = "${skill.skillName} — ${priority.label}",
            fontWeight = FontWeight.SemiBold,
        )
        Text(
            text = "Situation: $situation",
            style = MaterialTheme.typography.bodySmall,
        )
        skill.headings.forEach { h ->
            Text(
                text = "$h:",
                fontWeight = FontWeight.Medium,
            )
        }
    }
}
