#!/usr/bin/env python3
"""Regenerates docs/CLINICIAN_PACK.md from the app's own strings.

Every user-facing sentence, grouped by feature, in one document — so the
clinical review this project has always named as outstanding costs a
reader about an hour instead of an afternoon of code spelunking. Run it
after any wording change; the document says at the top when it was last
regenerated against which strings.
"""
import re
import sys
import hashlib
import pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
STRINGS = ROOT / "app/src/main/res/values/strings.xml"
OUT = ROOT / "docs/CLINICIAN_PACK.md"

GROUPS = [
    ("Highest priority — read these first", (
        "deviation", "sleep_late", "report_", "pattern_", "facts_",
        "pulse_", "ema_", "support_", "plan_", "dial_",
    ), "These reach a person about their own mind, sleep or mood, "
       "possibly on a bad day. The test for each line: could it read as "
       "reproach, alarm, or diagnosis to somebody already keeping score "
       "against themselves?"),
    ("The pauses and small helps", (
        "friction", "intention", "breath_", "session_", "small_thing",
        "loop_", "stale_", "watch_",
    ), "Interruptions the app itself creates. The test: does the wording "
       "ask, or does it tell? Nothing here may shame a choice."),
    ("Quiet, batching and the phone itself", (
        "batching_", "digest_", "sunset_", "grayscale", "owner_",
        "appearance_", "scene_", "goal", "onboarding", "settings",
        "corpus_", "model_", "arriving_", "probe_", "source_", "backup_",
        "signal_", "about", "action_", "greeting", "time_", "grant_",
        "is_default", "set_default", "open_", "search_", "app_name",
        "never_mind", "ppg_", "who5",
    ), "Mechanics and settings. Lower stakes, still worth a pass for "
       "anything that overpromises or scolds."),
]


def parse(path):
    # Use utf-8 explicitly: Windows Python's default locale
    # encoding (cp1252) mis-decodes the smart quotes / em-dashes
    # that the strings table carries.
    text = path.read_text(encoding="utf-8")
    out = []
    for m in re.finditer(r'<string name="([^"]+)">(.*?)</string>', text, re.S):
        name, body = m.group(1), m.group(2)
        body = body.replace("\\'", "'").replace("\\&#39;", "'").replace('\\"', '"')
        out.append((name, body))
    return out


def bucket(name):
    for index, (_, prefixes, _) in enumerate(GROUPS):
        if any(name.startswith(p) or p in name for p in prefixes):
            return index
    return len(GROUPS) - 1


def main():
    strings = parse(STRINGS)
    digest = hashlib.sha256(STRINGS.read_bytes()).hexdigest()[:12]
    lines = []
    lines.append("# Clinician review pack\n")
    lines.append(
        "Generated by `tools/clinician-pack.py` — do not edit by hand; "
        f"regenerate after wording changes. Source `strings.xml` digest: `{digest}`.\n"
    )
    lines.append(
        "## What this app promises about wording\n\n"
        "One rule shapes every sentence: research in the app says what a\n"
        "signal *is*, the person's own history says it *moved*, and nothing\n"
        "anywhere says what that *means about them*. No diagnosis, no risk\n"
        "language, no praise or blame, no streaks, no badges. Empty states\n"
        "are treated as ordinary. If a line below breaks that rule, it is a\n"
        "bug of exactly the kind this review exists to catch.\n"
    )
    lines.append(
        "## How to review\n\n"
        "Read each line as three people: someone having an ordinary day,\n"
        "someone in a depressive episode who is keeping score against\n"
        "themselves, and someone recently bereaved whose sleep and numbers\n"
        "are legitimately terrible. Flag anything that reads as reproach,\n"
        "alarm, cheerfulness at the wrong moment, or certainty the data\n"
        "cannot carry.\n"
    )
    buckets = {i: [] for i in range(len(GROUPS))}
    for name, body in strings:
        buckets[bucket(name)].append((name, body))
    for index, (title, _, note) in enumerate(GROUPS):
        lines.append(f"\n## {title}\n\n{note}\n")
        for name, body in buckets[index]:
            clean = " ".join(body.split())
            lines.append(f"- **`{name}`** — {clean}")
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {OUT} with {len(strings)} strings, digest {digest}")


if __name__ == "__main__":
    sys.exit(main())
